added CVE IDs
owncloud/security-advisories-old pull request #11
Opened 2017-02-03 07:22 UTC by Peter-Prochaska

2017-02-03 09:04 UTC, PVince81 commented
:+1:

2017-02-08 14:33 UTC, DeepDiver1975 requested changes

2017-02-08 14:33 UTC, DeepDiver1975 commented on server/oc-sa-2017-002.json
> +      "CVE": " CVE-2017-5866",
whitespace?

2017-02-09 08:58 UTC, DeepDiver1975 approved these changes

2017-02-09 08:58 UTC, merged