Security fixes 2017-05
owncloud/security-advisories-old pull request #12
Opened 2017-06-01 06:44 UTC by Peter-Prochaska

added new security advisories

2017-06-01 07:06 UTC, DeepDiver1975 requested changes

2017-06-01 07:06 UTC, DeepDiver1975 commented on server/oc-sa-2017-007.json
> +    "name": "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')a"
)a ❓

2017-06-01 07:06 UTC, DeepDiver1975 commented on server/oc-sa-2017-007.json
> +      "HoF": true
HoF is not needed anymore

2017-06-01 08:31 UTC, LukasReschke requested changes
It seems like you forgot to add a reference to the source as well as a notice as required by CC BY-SA 4.0. I've left a friendly reminder where I feel Nextcloud should be credited. 

In the future, I would expect that this happens without a notification from my side.

Thank you.

2017-06-01 08:31 UTC, LukasReschke commented on server/oc-sa-2017-005.json
> +  "Description":"<p>A logical error caused disclosure of valid share tokens for public calendars. Thus granting an attacker potentially access to publicly shared calendars without knowing the share t
Another friendly reminder that advisories by Nextcloud are licensed CC BY-SA 4.0. This text block is copied verbatim from https://nextcloud.com/security/advisory/?id=nc-sa-2017-011 and a Google search has shown that this word combination cannot be found somewhere else in the internet.

We expect to be credited here properly. Thank you. To comply with this licensing issue I'd like to ask you to add `"ncAdvisory": "nc-sa-2017-011",`

2017-06-01 08:31 UTC, LukasReschke commented on server/oc-sa-2017-007.json
> +  "Description":"<p>Inadequate escaping lead to XSS vulnerability in the search module. To be exploitable an user has to write or paste malicious content into the search dialogue.</p>",
Another friendly reminder that advisories by Nextcloud are licensed CC BY-SA 4.0. This text block is copied verbatim from https://nextcloud.com/security/advisory/?id=nc-sa-2017-007 and a Google search has shown that this word combination cannot be found somewhere else in the internet.

We expect to be credited here properly. Thank you. To comply with this licensing issue I'd like to ask you to add `"ncAdvisory": "nc-sa-2017-007",`

2017-06-01 08:43 UTC, LukasReschke commented on generator/generate.php
> +            file_put_contents('./out/' . substr($fileinfo, 0, -5) . '.txt', $content);
Looking at the code, this new text file doesn't contain copyright notes as per https://github.com/owncloud/security-advisories/pull/12/files#diff-064b2076f78171f7d4d71a8f1d35b1deR147 – please make sure to include this in all user-accessible formats. Thanks.

2017-06-01 10:26 UTC, Peter-Prochaska commented on server/oc-sa-2017-005.json
> +  "Description":"<p>A logical error caused disclosure of valid share tokens for public calendars. Thus granting an attacker potentially access to publicly shared calendars without knowing the share t
done. sorry

2017-06-01 10:26 UTC, Peter-Prochaska commented on server/oc-sa-2017-007.json
> +  "Description":"<p>Inadequate escaping lead to XSS vulnerability in the search module. To be exploitable an user has to write or paste malicious content into the search dialogue.</p>",
done

2017-06-01 10:26 UTC, LukasReschke commented
Thanks @Peter-Prochaska.

2017-06-01 10:29 UTC, Peter-Prochaska commented
your are welcome @LukasReschke

2017-07-04 09:55 UTC, PVince81 commented
merge then ?

2019-02-05 14:02 UTC, PVince81 commented
old ? close ? @DeepDiver1975 @settermjd

2019-02-06 08:56 UTC, DeepDiver1975 commented
No damn idea

2021-04-13 07:53 UTC, closed without merging